# Generated by Django 6.0.1 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employeeid',
            field=models.IntegerField(null=True),
        ),
    ]
