# Generated by Django 6.0.1 on 2026-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=110)),
                ('studentage', models.IntegerField()),
                ('studentcity', models.CharField(max_length=50)),
                ('studentemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
