# Generated by Django 6.0.1 on 2026-02-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_prduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prduct',
            new_name='product',
        ),
    ]
