# Generated by Django 6.0.1 on 2026-02-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_prduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcolor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
