# Generated by Django 6.0.1 on 2026-02-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_age', models.IntegerField()),
                ('employee_role', models.CharField(max_length=50)),
                ('employee_salary', models.IntegerField()),
                ('employee_exp', models.IntegerField()),
            ],
        ),
    ]
