# Generated by Django 6.0.1 on 2026-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(null=True),
        ),
    ]
