# Generated by Django 6.0.1 on 2026-02-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_employee_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenthobbies', models.CharField(choices=[('reading', 'reading'), ('travel', 'travel'), ('music', 'music')], max_length=50)),
                ('studentaddress', models.CharField(max_length=100)),
                ('studentphone', models.IntegerField()),
                ('studentgender', models.CharField(max_length=30)),
                ('studentDOB', models.DateField()),
                ('studentid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
