# Generated by Django 6.0.1 on 2026-02-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='studentprofile',
        ),
    ]
