# Generated by Django 6.0.1 on 2026-02-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_category_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
