# Generated by Django 6.0.1 on 2026-02-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stu',
        ),
    ]
