# Generated by Django 6.0.1 on 2026-02-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
